    k8s:
      application:
        components:
          web:
            settings:
              cpu:
                min: 0.125
                max: 1.0
              replicas:
                min: 1
                max: 4
    prom:
      prometheus_endpoint: 'http://prometheus.svc.opsani-monitoring:9090'
      metrics: 
        main_request_rate: 
          query: 'sum(rate(envoy_cluster_upstream_rq_total{app="web",role="main"}[1m]))'
          unit: rps
        main_p90_time:
          query: 'histogram_quantile(0.9,sum(rate(envoy_cluster_external_upstream_rq_time_bucket{app="web",role="main"}[1m])) by (envoy_cluster_name, le))'
          unit: ms
        main_error_rate:
          query: 'sum(rate(envoy_cluster_external_upstream_rq_xx{app="web",envoy_response_code_class!="2",role="main"}[1m]))'
          unit: rpm
        main_median_response_time:
          query: 'avg(histogram_quantile(0.5,rate(envoy_cluster_external_upstream_rq_time_bucket{app="web",role="main"}[1m])))'
          unit: ms
    vegeta:
        rate: 30000/m
        duration: 10m
        target: GET https://web:80/
        workers: 50
        max-workers: 5000
        interactive: true
